steps:
  # Build the Docker Compose services
  - name: 'docker/compose:1.26.2'
    entrypoint: '/bin/sh'  # Use the shell available in Alpine Linux
    args:
      - '-c'
      - |
        docker-compose build \
          --build-arg PROJECT_ID=hackyeah-breakthewordstraps-11 \
          --build-arg SHORT_SHA=breakthewordstraps

  # Tag the built images with the desired tags
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'myimage-backend:latest', 'europe-west1-docker.pkg.dev/hackyeah-breakthewordstraps-11/ujo142/breakbordsbraps/backend/myimage-backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'myimage-interface:latest', 'europe-west1-docker.pkg.dev/hackyeah-breakthewordstraps-11/ujo142/breakwordsbraps/interface/myimage-interface']

  # Push the tagged images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/hackyeah-breakthewordstraps-11/ujo142/breakwordstraps/backend/myimage-backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/hackyeah-breakthewordstraps-11/ujo142/breakwordstraps/interface/myimage-interface']