FROM python:3.11

RUN mkdir /backend


COPY requirements.txt /backend
RUN !python3 -m spacy download pl_core_news_sm

WORKDIR /backend

RUN pip install -r requirements.txt


COPY . /backend

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


