FROM python:3.11

ENV PORT=8080

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install -r requirements.txt

RUN python3 -m spacy download pl_core_news_sm

WORKDIR /app

COPY . .

EXPOSE 8080

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]


