FROM python:3.11

RUN mkdir /interface

ENV PORT=8080

RUN pip install streamlit

RUN which streamlit

COPY requirements.txt /interface

WORKDIR /interface

RUN pip install -r requirements.txt

COPY . /interface

# EXPOSE 8501
EXPOSE 8080

#CMD streamlit run --server.port $PORT app.py
CMD ["streamlit", "run", "--server.port", "8080", "app.py"]